/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        void: "#000000",
        carbon: "#121212",
        chalk: "#FFFFFF",
        volt: "#CCFF00",
        pit: "#475569",
        border: "#000000",
        input: "#000000",
        ring: "#CCFF00",
        background: "#121212",
        foreground: "#FFFFFF",
        primary: { DEFAULT: "#CCFF00", foreground: "#000000" },
        secondary: { DEFAULT: "#FFFFFF", foreground: "#000000" },
        destructive: { DEFAULT: "#FF3131", foreground: "#FFFFFF" },
        muted: { DEFAULT: "#121212", foreground: "#FFFFFF" },
        accent: { DEFAULT: "#CCFF00", foreground: "#000000" },
        popover: { DEFAULT: "#FFFFFF", foreground: "#000000" },
        card: { DEFAULT: "#FFFFFF", foreground: "#000000" },
      },
      fontFamily: {
        display: ["Ranchers", "Impact", "sans-serif"],
        mono: ["'Space Mono'", "ui-monospace", "Menlo", "monospace"],
        body: ["'Plus Jakarta Sans'", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "hero-xl": ["180px", { lineHeight: "0.85", letterSpacing: "-0.01em" }],
        "hero-lg": ["150px", { lineHeight: "0.85", letterSpacing: "-0.01em" }],
        "hero-md": ["120px", { lineHeight: "0.85", letterSpacing: "-0.01em" }],
        "hero-sm": ["80px", { lineHeight: "0.9", letterSpacing: "0" }],
        "display-xl": ["64px", { lineHeight: "1", letterSpacing: "0" }],
        "display-md": ["48px", { lineHeight: "1.05", letterSpacing: "0" }],
        "display-sm": ["32px", { lineHeight: "1.1", letterSpacing: "0" }],
        "mono-xl": ["24px", { lineHeight: "1.2", letterSpacing: "0.1em" }],
        "mono-lg": ["18px", { lineHeight: "1.3", letterSpacing: "0.1em" }],
        "mono-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.1em" }],
        "mono-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.15em" }],
        "mono-xs": ["10px", { lineHeight: "1.4", letterSpacing: "0.2em" }],
      },
      borderWidth: {
        "hard-sm": "4px",
        "hard-lg": "8px",
      },
      borderRadius: {
        brutal: "0px",
        slight: "8px",
        lg: "0px",
        md: "0px",
        sm: "0px",
      },
      boxShadow: {
        "neo-dark": "8px 8px 0 0 #000000",
        "neo-dark-sm": "4px 4px 0 0 #000000",
        "neo-light": "8px 8px 0 0 #FFFFFF",
        "neo-light-sm": "4px 4px 0 0 #FFFFFF",
        "neo-volt": "8px 8px 0 0 #CCFF00",
        "neo-pressed": "0 0 0 0 #000000",
      },
      rotate: {
        "sticker-cw": "3deg",
        "sticker-ccw": "-2deg",
        "sticker-hi": "5deg",
        "sticker-lo": "-3deg",
        "logo-sq": "3deg",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "slam-in": { "0%": { transform: "scale(1.8)" }, "100%": { transform: "scale(1)" } },
        "clip-reveal": { "0%": { clipPath: "inset(0 100% 0 0)" }, "100%": { clipPath: "inset(0 0 0 0)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slam-in": "slam-in 0.25s cubic-bezier(0.25,0.46,0.45,0.94)",
        "clip-reveal": "clip-reveal 0.18s cubic-bezier(0.25,0.46,0.45,0.94)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
